version: "3.9"
services:
  app:
    build: .
    ports:
    - "5000:5000"
    environment:
      - FLASK_DEBUG=1
    volumes:
    - .:/app
  db:
    image: "mysql:8.0.25"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: appmy
      MYSQL_USER: app
      MYSQL_PASSWORD: app123
    volumes:
      - ./data_db:/var/lib/mysql
